org.gradle.jvmargs = -Xmx2G

# Mod metadata
mod.name        = CraftGR
mod.id          = craftgr
mod.group       = sh.kaban.craftgr
mod.version     = 2.0.0
mod.description = Touhou Project music player for Minecraft
mod.authors     = KabanFriends
mod.license     = LGPL-3.0
mod.website     = https://modrinth.com/mod/craftgr
mod.source      = https://github.com/KabanFriends/CraftGR
mod.issues      = https://github.com/KabanFriends/CraftGR/issues

# Stonecutter
stonecutter_platforms         = fabric, neoforge
stonecutter_common_versions   = 1.21.1, 1.21.11, 26.2, 26.3
stonecutter_fabric_versions   = 1.21.1, 1.21.11, 26.2, 26.3
stonecutter_neoforge_versions = 1.21.1, 1.21.11, 26.2, 26.3

# The below field are intentionally left blank,
# to edit, please edit gradle.properties for each versions.

# Java
java.version =

# Minecraft
deps.minecraft =
deps.parchment =

# Fabric
deps.fabric-loader =
deps.fabric-api    =

# NeoForge
deps.neoforge =

# Dependencies
deps.yacl    =
deps.modmenu =
