# Stonecutter
stonecutter_platforms = fabric, neoforge

# Java
java.version = 21

# Minecraft
deps.minecraft = 1.21.11
deps.parchment = 2025.12.20

# Fabric
deps.fabric-loader = 0.18.0
deps.fabric-api    = 0.141.6+1.21.11

# NeoForge
deps.neoforge = 21.11.45

# Dependencies
deps.yacl    = 3.8.2+1.21.11
deps.modmenu = 17.0.0
