modLoader = "javafml"
loaderVersion = "[1,)"
issueTrackerURL = "https://github.com/KabanFriends/CraftGR/issues"
license = "LGPL-3.0"

[[mods]]
modId = "craftgr"
version = "${version}"
displayName = "CraftGR"
authors = "KabanFriends"
description = "Touhou Project music player for Minecraft"
modUrl = "https://modrinth.com/mod/craftgr"
logoFile = "icon.png"

[[mixins]]
config = "craftgr-common.mixins.json"

[[dependencies.craftgr]]
modId = "minecraft"
type = "required"
versionRange = "[1.20.4,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.craftgr]]
modId = "neoforge"
type = "required"
versionRange = "[20.4.40,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.craftgr]]
modId = "yet_another_config_lib_v3"
type = "optional"
versionRange="[3.4.0,)"
ordering = "NONE"
side = "CLIENT"
