modLoader = "javafml"
loaderVersion = "[1,)"
issueTrackerURL = "${modIssues}"
license = "LGPL-3.0"

[[mods]]
modId = "${modId}"
version = "${modVersion}+mc${stonecutterVersion}"
displayName = "${modName}"
authors = "${modAuthors}"
description = "${modDescription}"
modUrl = "${modWebsite}"
logoFile = "icon.png"

[[mixins]]
config = "craftgr-common.mixins.json"

[[dependencies.craftgr]]
modId = "minecraft"
type = "required"
versionRange = "[${minecraftVersion},)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.craftgr]]
modId = "neoforge"
type = "required"
versionRange = "[${neoforgeVersion},)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.craftgr]]
modId = "yet_another_config_lib_v3"
type = "optional"
versionRange="[${yaclVersion},)"
ordering = "NONE"
side = "CLIENT"
