# Stonecutter
stonecutter_platforms = fabric, neoforge

# Java
java.version = 25

# Minecraft
deps.minecraft = 26.3

# Fabric
deps.fabric-loader = 0.19.5
deps.fabric-api    = 0.161.0+26.3

# NeoForge
deps.neoforge = 26.3.0.3-beta

# Dependencies
deps.yacl    = 3.9.4+26.2
deps.modmenu = 21.0.0-beta.1
