# Stonecutter
stonecutter_platforms = fabric, neoforge

# Java
java.version = 21

# Minecraft
deps.minecraft = 1.21.1
deps.parchment = 2024.11.17

# Fabric
deps.fabric-loader = 0.15.11
deps.fabric-api    = 0.116.17+1.21.1

# NeoForge
deps.neoforge = 21.1.251

# Dependencies
deps.yacl    = 3.8.2+1.21.1
deps.modmenu = 11.0.4
