name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17
          check-latest: true
      - name: Build using Gradle
        run: |
          chmod +x ./gradlew
          ./gradlew build
      - name: Upload Fabric artifacts
        uses: actions/upload-artifact@v3
        with:
          name: fabric
          path: fabric/build/libs/
      - name: Upload Forge artifacts
        uses: actions/upload-artifact@v3
        with:
          name: forge
          path: forge/build/libs/
      - name: Upload NeoForge artifacts
        uses: actions/upload-artifact@v3
        with:
          name: neoforge
          path: neoforge/build/libs/
      - name: Upload merged artifact
        uses: actions/upload-artifact@v3
        with:
          name: merged
          path: build/libs/merged/