name: Build

on:
  push:
    branches:
      - "*"
  pull_request:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 21
          check-latest: true
      - name: Build with Gradle
        run: |
          chmod +x ./gradlew
          ./gradlew build
      - name: Upload Fabric artifact
        uses: actions/upload-artifact@v3
        with:
          name: fabric
          path: fabric/build/libs/
      - name: Upload NeoForge artifact
        uses: actions/upload-artifact@v3
        with:
          name: neoforge
          path: neoforge/build/libs/
