name: Create Release

on: workflow_dispatch

jobs:
  release:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Read mod properties
        id: mod_properties
        uses: christian-draeger/read-properties@1.1.1
        with:
          path: gradle.properties
          properties: mod_version
      - name: Read Minecraft version
        id: minecraft_version
        uses: SebRollen/toml-action@v1.2.0
        with:
          file: "gradle/libs.versions.toml"
          field: "versions.minecraft"
      - name: Create a release
        uses: softprops/action-gh-release@v2.3.2
        with:
          tag_name: "${{ steps.mod_properties.outputs.mod_version }}-mc${{ steps.minecraft_version.outputs.value }}"
          name: "${{ steps.mod_properties.outputs.mod_version }}-mc${{ steps.minecraft_version.outputs.value }}"
          body: No changelog available.
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
